---
- name: Install bind-utils package in linux
  hosts: Webservers
  become: true
  tasks:
    - name: Install in Centos OS.
      yum: 
       name: bind-utils
      when: ansible_os_family=="RedHat"